name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Change to use Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest

      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo $env:KUBE_CONFIG_DATA | base64 --decode > kubeconfig  # Adjusted for Windows
          kubectl --kubeconfig=kubeconfig apply -f k8s-deployment.yaml --validate=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          privileged: false

